# Generated by Django 3.1.5 on 2021-02-18 23:26

import POS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Image',
            field=models.ImageField(default='', upload_to=POS.models.image_upload),
            preserve_default=False,
        ),
    ]
