# Generated by Django 3.1.5 on 2021-02-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area_name',
            field=models.CharField(default=215, max_length=50),
            preserve_default=False,
        ),
    ]
