# Generated by Django 3.1.7 on 2021-03-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_itemlocation_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlocation',
            name='location_name',
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
