# Generated by Django 3.1.5 on 2021-04-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0009_auto_20210330_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
